package toml

import "testing"

func TestParseCargoLockShape(t *testing.T) {
	const src = `
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "aho-corasick"
version = "1.1.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8e60d3430d3a69478ad0993f19238d2df97c507009a52b3c10addcd7f6bcb916"
dependencies = [
 "memchr",
]

[[package]]
name = "memchr"
version = "2.7.4"
`
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if v, _ := root["version"].(int64); v != 3 {
		t.Errorf("version = %v, want 3", root["version"])
	}
	pkgs := Tables(root["package"])
	if len(pkgs) != 2 {
		t.Fatalf("got %d packages, want 2", len(pkgs))
	}
	if name, _ := String(pkgs[0]["name"]); name != "aho-corasick" {
		t.Errorf("pkg[0].name = %v", pkgs[0]["name"])
	}
	if ver, _ := String(pkgs[0]["version"]); ver != "1.1.3" {
		t.Errorf("pkg[0].version = %v", pkgs[0]["version"])
	}
	if deps := Strings(pkgs[0]["dependencies"]); len(deps) != 1 || deps[0] != "memchr" {
		t.Errorf("pkg[0].dependencies = %v", deps)
	}
	if name, _ := String(pkgs[1]["name"]); name != "memchr" {
		t.Errorf("pkg[1].name = %v", pkgs[1]["name"])
	}
}

func TestParseInlineTableAndDottedKeys(t *testing.T) {
	// uv.lock uses inline tables for `source`; poetry.lock uses dotted
	// sub-tables for metadata.
	const src = `
version = 1

[[package]]
name = "click"
version = "8.1.7"
source = { registry = "https://pypi.org/simple" }

[metadata]
lock-version = "2.0"

[metadata.files]
click = []
`
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	pkgs := Tables(root["package"])
	if len(pkgs) != 1 {
		t.Fatalf("got %d packages, want 1", len(pkgs))
	}
	src2, ok := Table(pkgs[0]["source"])
	if !ok {
		t.Fatalf("source is not an inline table: %T", pkgs[0]["source"])
	}
	if reg, _ := String(src2["registry"]); reg != "https://pypi.org/simple" {
		t.Errorf("source.registry = %v", src2["registry"])
	}
	if lv, _ := String(Get(root, "metadata.lock-version")); lv != "2.0" {
		t.Errorf("metadata.lock-version = %v", Get(root, "metadata.lock-version"))
	}
	if Get(root, "metadata.files.click") == nil {
		t.Error("metadata.files.click should be present")
	}
}

// Julia's Manifest.toml keys array-of-tables entries by a dotted path, so
// the header parser has to create intermediate tables before appending.
func TestParseDottedArrayOfTables(t *testing.T) {
	const src = `
julia_version = "1.10.0"
manifest_format = "2.0"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.1"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
`
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	deps, ok := Table(root["deps"])
	if !ok {
		t.Fatalf("deps is not a table: %T", root["deps"])
	}
	argTools := Tables(deps["ArgTools"])
	if len(argTools) != 1 {
		t.Fatalf("got %d ArgTools entries, want 1", len(argTools))
	}
	if v, _ := String(argTools[0]["version"]); v != "1.1.1" {
		t.Errorf("ArgTools version = %v", argTools[0]["version"])
	}
	if len(Tables(deps["Base64"])) != 1 {
		t.Error("Base64 entry missing")
	}
}

// Codex writes its MCP servers as nested tables with array values.
func TestParseNestedTableWithArray(t *testing.T) {
	const src = `
[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]

[mcp_servers.local]
command = "/usr/local/bin/thing"
`
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	servers, ok := Table(root["mcp_servers"])
	if !ok {
		t.Fatalf("mcp_servers is not a table: %T", root["mcp_servers"])
	}
	pw, ok := Table(servers["playwright"])
	if !ok {
		t.Fatal("playwright entry missing")
	}
	if cmd, _ := String(pw["command"]); cmd != "npx" {
		t.Errorf("command = %v", pw["command"])
	}
	args := Strings(pw["args"])
	if len(args) != 2 || args[1] != "@playwright/mcp@latest" {
		t.Errorf("args = %v", args)
	}
	if len(servers) != 2 {
		t.Errorf("got %d servers, want 2", len(servers))
	}
}

func TestParseStringForms(t *testing.T) {
	const src = "basic = \"a\\tb\"\nliteral = 'c\\td'\nmulti = \"\"\"\nline1\nline2\"\"\"\nmultilit = '''\nraw\\n'''\nuni = \"\\u0041\"\n"
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	cases := map[string]string{
		"basic":    "a\tb",
		"literal":  `c\td`,
		"multi":    "line1\nline2",
		"multilit": `raw\n`,
		"uni":      "A",
	}
	for key, want := range cases {
		got, _ := String(root[key])
		if got != want {
			t.Errorf("%s = %q, want %q", key, got, want)
		}
	}
}

func TestParseScalarTypes(t *testing.T) {
	const src = `
int = 42
neg = -7
under = 1_000
float = 3.14
yes = true
no = false
hex = 0xff
when = 2026-05-28T10:00:00Z
`
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if root["int"] != int64(42) || root["neg"] != int64(-7) || root["under"] != int64(1000) {
		t.Errorf("integers = %v %v %v", root["int"], root["neg"], root["under"])
	}
	if root["float"] != 3.14 {
		t.Errorf("float = %v", root["float"])
	}
	if root["yes"] != true || root["no"] != false {
		t.Errorf("bools = %v %v", root["yes"], root["no"])
	}
	if root["hex"] != int64(255) {
		t.Errorf("hex = %v", root["hex"])
	}
	// Dates are deliberately left as raw text.
	if s, _ := String(root["when"]); s != "2026-05-28T10:00:00Z" {
		t.Errorf("when = %v", root["when"])
	}
}

func TestParseComomentsAndTrailingCommas(t *testing.T) {
	const src = `
# leading comment
a = [ "x", "y", ] # trailing comment
[t] # header comment
b = 1
`
	root, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if got := Strings(root["a"]); len(got) != 2 || got[0] != "x" || got[1] != "y" {
		t.Errorf("a = %v", got)
	}
	if Get(root, "t.b") != int64(1) {
		t.Errorf("t.b = %v", Get(root, "t.b"))
	}
}

func TestParseRejectsMalformed(t *testing.T) {
	bad := []string{
		`a = `,
		`[unterminated`,
		`a = "no end`,
		`= 1`,
		`a = 'newline
in literal'`,
	}
	for _, src := range bad {
		if _, err := Parse([]byte(src)); err == nil {
			t.Errorf("Parse(%q) succeeded, want error", src)
		}
	}
}

func TestGetMissingPathReturnsNil(t *testing.T) {
	root, err := Parse([]byte("a = 1\n"))
	if err != nil {
		t.Fatal(err)
	}
	if Get(root, "a.b.c") != nil {
		t.Error("descending into a scalar should yield nil")
	}
	if Get(root, "nope") != nil {
		t.Error("missing key should yield nil")
	}
}
