package toml

import "testing"

func TestParseCargoLockShape(t *testing.T) {
	in := []byte(`# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7253ab4de971e72fb7be983802300c30b5a7f0c2e56fab8abfc6a214307c0094"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.203"
`)
	doc, err := Parse(in)
	if err != nil {
		t.Fatal(err)
	}
	pkgs := doc.TablesNamed("package")
	if len(pkgs) != 2 {
		t.Fatalf("want 2 packages, got %d", len(pkgs))
	}
	if got := pkgs[0].String("name"); got != "serde" {
		t.Errorf("name=%q", got)
	}
	if got := pkgs[0].String("version"); got != "1.0.203" {
		t.Errorf("version=%q", got)
	}
	deps := pkgs[0].Values["dependencies"]
	if deps.Kind != KindStrings || len(deps.Strings) != 1 || deps.Strings[0] != "serde_derive" {
		t.Errorf("dependencies=%+v", deps)
	}
	if v := doc.Root["version"]; v.Kind != KindInt || v.Int != 3 {
		t.Errorf("root version=%+v", v)
	}
}

// poetry.lock puts an array of inline tables on every package. That must
// not make the file unreadable — name and version parse fine.
func TestParsePoetryLockShape(t *testing.T) {
	in := []byte(`[[package]]
name = "requests"
version = "2.32.3"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.8"
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:abc"},
    {file = "requests-2.32.3.tar.gz", hash = "sha256:def"},
]

[package.dependencies]
certifi = ">=2017.4.17"
charset-normalizer = {version = ">=2", markers = "python_version < \"3.10\""}

[[package]]
name = "certifi"
version = "2024.7.4"
files = []
`)
	doc, err := Parse(in)
	if err != nil {
		t.Fatal(err)
	}
	pkgs := doc.TablesNamed("package")
	if len(pkgs) != 2 {
		t.Fatalf("want 2 packages, got %d: %+v", len(pkgs), doc.Tables)
	}
	if pkgs[0].String("name") != "requests" || pkgs[0].String("version") != "2.32.3" {
		t.Errorf("pkg0=%+v", pkgs[0])
	}
	if pkgs[1].String("name") != "certifi" || pkgs[1].String("version") != "2024.7.4" {
		t.Errorf("pkg1=%+v", pkgs[1])
	}
	// The unsupported value is recorded, not dropped.
	if v, ok := pkgs[0].Values["files"]; !ok || v.Kind != KindUnsupported {
		t.Errorf("files should be recorded as unsupported, got %+v (present=%v)", v, ok)
	}
	// A sub-table must not be mistaken for another package.
	if len(doc.TablesNamed("package.dependencies")) != 1 {
		t.Errorf("package.dependencies table missing")
	}
}

func TestParseQuotingAndComments(t *testing.T) {
	in := []byte(`bare = "value # not a comment"
literal = 'C:\Users\alex\path'
escaped = "line\nbreak"
"quoted key" = "v"
flag = true
empty_array = []
# whole-line comment
trailing = "x" # comment
`)
	doc, err := Parse(in)
	if err != nil {
		t.Fatal(err)
	}
	cases := map[string]string{
		"bare":       "value # not a comment",
		"literal":    `C:\Users\alex\path`,
		"escaped":    "line\nbreak",
		"quoted key": "v",
		"trailing":   "x",
	}
	for k, want := range cases {
		if got := doc.Root[k].Str; got != want {
			t.Errorf("%s = %q, want %q", k, got, want)
		}
	}
	if v := doc.Root["flag"]; v.Kind != KindBool || !v.Bool {
		t.Errorf("flag=%+v", v)
	}
	if v := doc.Root["empty_array"]; v.Kind != KindStrings || len(v.Strings) != 0 {
		t.Errorf("empty_array=%+v", v)
	}
}

// Structural damage must be a hard error, so a caller reports the file
// as unparsed rather than emitting a partial package list as complete.
func TestParseStructuralErrors(t *testing.T) {
	cases := map[string]string{
		"malformed table header": "[package\nname = \"x\"\n",
		"not an assignment":      "[[package]]\nname\n",
		"unterminated string":    "[[package]]\nname = \"x\n",
		"dotted key":             "[[package]]\na.b = \"x\"\n",
	}
	for name, in := range cases {
		if _, err := Parse([]byte(in)); err == nil {
			t.Errorf("%s: want error, got nil", name)
		}
	}
}

// Both cases below came from real lockfiles on real machines, and both
// made Parse reject the ENTIRE file. In a scanner that is the worst
// failure mode there is: every package in the file disappears and the
// endpoint reports clean.

// uv.lock nests an array inside an array of inline tables. The inner
// "]" must not be mistaken for the end of the outer array.
func TestParseUVLockNestedBrackets(t *testing.T) {
	in := []byte(`[[package]]
name = "mcp-server-odp"
version = "0.1.0"
dependencies = [
    { name = "pydantic", extra = ["email"] },
    { name = "httpx" },
]

[[package]]
name = "httpx"
version = "0.27.0"
`)
	doc, err := Parse(in)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got := len(doc.TablesNamed("package")); got != 2 {
		t.Fatalf("want 2 packages, got %d", got)
	}
	if doc.TablesNamed("package")[1].String("name") != "httpx" {
		t.Error("second package lost")
	}
}

// Cargo.lock v1 [metadata] uses quoted keys that contain dots. Only a
// BARE key is forbidden from containing them.
func TestParseCargoLockV1MetadataQuotedKeys(t *testing.T) {
	in := []byte(`[[package]]
name = "libc"
version = "0.2.155"

[metadata]
"checksum rustc-std-workspace-core 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = "1dcc"
`)
	doc, err := Parse(in)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got := len(doc.TablesNamed("package")); got != 1 {
		t.Fatalf("want 1 package, got %d", got)
	}
	meta := doc.TablesNamed("metadata")
	if len(meta) != 1 || len(meta[0].Values) != 1 {
		t.Fatalf("metadata table not parsed: %+v", meta)
	}
}
