package cargo

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/perplexityai/bumblebee/internal/model"
)

func TestScanCargoLock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")
	body := `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "7253ab4de971e72fb7be983802300c30b5a7f0c2e56fab8abfc6a214307c0094"
dependencies = [
 "serde_derive",
]

[[package]]
name = "my-workspace-crate"
version = "0.1.0"

[[package]]
name = "serde_derive"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	var out []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { out = append(out, r) }}
	if err := s.ScanCargoLock(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(out) != 3 {
		t.Fatalf("want 3 records, got %d: %+v", len(out), out)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].PackageName < out[j].PackageName })

	// A workspace member has no `source`, so it is not something a
	// crates.io advisory can name.
	if out[0].PackageName != "my-workspace-crate" || out[0].Confidence != "medium" {
		t.Errorf("workspace member: %+v", out[0])
	}
	if out[1].PackageName != "serde" || out[1].Version != "1.0.203" || out[1].Confidence != "high" {
		t.Errorf("serde: %+v", out[1])
	}
	// crates.io treats - and _ as equivalent for uniqueness.
	if out[0].NormalizedName != "my_workspace_crate" {
		t.Errorf("normalized=%q", out[0].NormalizedName)
	}
}

func TestIsRegistrySrcMarker(t *testing.T) {
	base := filepath.Join("home", ".cargo", "registry", "src", "index.crates.io-6f17d22bba15001f")
	cases := []struct {
		in      string
		ok      bool
		name    string
		version string
	}{
		{filepath.Join(base, "serde-1.0.203", "Cargo.toml"), true, "serde", "1.0.203"},
		// Crate names contain hyphens; the split is on the last one that
		// is followed by something version-shaped.
		{filepath.Join(base, "proc-macro2-1.0.86", "Cargo.toml"), true, "proc-macro2", "1.0.86"},
		{filepath.Join(base, "serde-1.0.203", "src", "Cargo.toml"), false, "", ""},
		{filepath.Join("home", "proj", "Cargo.toml"), false, "", ""},
		{filepath.Join(base, "noversion", "Cargo.toml"), false, "", ""},
	}
	for _, c := range cases {
		ok, name, version, _ := IsRegistrySrcMarker(c.in)
		if ok != c.ok || name != c.name || version != c.version {
			t.Errorf("IsRegistrySrcMarker(%q) = (%v, %q, %q), want (%v, %q, %q)",
				c.in, ok, name, version, c.ok, c.name, c.version)
		}
	}
}

func TestScanCargoLockStructuralErrorIsFatal(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")
	if err := os.WriteFile(path, []byte("[[package]]\nname = \"a\"\n\n[[package\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var out []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { out = append(out, r) }}
	if err := s.ScanCargoLock(path, model.Record{}); err == nil {
		t.Fatal("want error for malformed Cargo.lock")
	}
	if len(out) != 0 {
		t.Errorf("no records from an unparsed file, got %d", len(out))
	}
}
