package cargo

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/perplexityai/bumblebee/internal/model"
)

func TestScanCargoLock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")
	if err := os.WriteFile(path, []byte(`# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde_json"
version = "1.0.108"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3d1c7e3eac408d115102c4c24ad393e0821bb3a5df4d506a80f85f7a742a526b"

[[package]]
name = "my-workspace-crate"
version = "0.1.0"
`), 0o644); err != nil {
		t.Fatal(err)
	}

	var got []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { got = append(got, r) }}
	if err := s.ScanCargoLock(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("got %d records, want 2: %+v", len(got), got)
	}

	byName := map[string]model.Record{}
	for _, r := range got {
		byName[r.PackageName] = r
	}
	sj := byName["serde_json"]
	if sj.Version != "1.0.108" {
		t.Errorf("version = %q", sj.Version)
	}
	if sj.Ecosystem != model.EcosystemCratesIO {
		t.Errorf("ecosystem = %q", sj.Ecosystem)
	}
	// crates.io treats '_' and '-' as equivalent for collision purposes,
	// which is what typosquat catalogs key on.
	if sj.NormalizedName != "serde-json" {
		t.Errorf("normalized = %q, want serde-json", sj.NormalizedName)
	}
	if sj.InstallScope != "" {
		t.Errorf("registry crate should have no local scope, got %q", sj.InstallScope)
	}
	if sj.Confidence != "high" {
		t.Errorf("confidence = %q", sj.Confidence)
	}

	// A package with no `source` is a path/workspace member.
	ws := byName["my-workspace-crate"]
	if ws.InstallScope != "local" {
		t.Errorf("sourceless crate scope = %q, want local", ws.InstallScope)
	}
}

func TestScanCargoLockDeduplicates(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")
	if err := os.WriteFile(path, []byte(`
[[package]]
name = "dup"
version = "1.0.0"
source = "registry+https://example"

[[package]]
name = "dup"
version = "1.0.0"
source = "registry+https://example"
`), 0o644); err != nil {
		t.Fatal(err)
	}
	var got []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { got = append(got, r) }}
	if err := s.ScanCargoLock(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("got %d records, want 1 after dedupe", len(got))
	}
}

func TestMalformedLockWarnsRatherThanErrors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")
	if err := os.WriteFile(path, []byte("[[package\nname = "), 0o644); err != nil {
		t.Fatal(err)
	}
	var got []model.Record
	var warned bool
	s := &Scanner{
		MaxFileSize: 1 << 20,
		Emit:        func(r model.Record) { got = append(got, r) },
		Diag:        func(level, path, msg string) { warned = true },
	}
	if err := s.ScanCargoLock(path, model.Record{}); err != nil {
		t.Fatalf("unparseable lock should warn, not error: %v", err)
	}
	if !warned {
		t.Error("expected a diagnostic for unparseable lock")
	}
	if len(got) != 0 {
		t.Errorf("emitted %d records from malformed lock", len(got))
	}
}
