package dartelixir

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/perplexityai/bumblebee/internal/model"
)

func run(t *testing.T, name, body string, fn func(*Scanner, string, model.Record) error) []model.Record {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	var out []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { out = append(out, r) }}
	if err := fn(s, path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].PackageName < out[j].PackageName })
	return out
}

func TestScanPubspecLock(t *testing.T) {
	body := `# Generated by pub
packages:
  crypto:
    dependency: "direct main"
    description:
      name: crypto
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.3"
  lints:
    dependency: "direct dev"
    source: hosted
    version: "4.0.0"
  my_local:
    dependency: "direct main"
    description:
      path: "../local"
    source: path
    version: "0.0.1"
sdks:
  dart: ">=3.4.0 <4.0.0"
`
	out := run(t, "pubspec.lock", body, (*Scanner).ScanPubspecLock)
	if len(out) != 3 {
		t.Fatalf("want 3 records, got %d: %+v", len(out), out)
	}
	byName := map[string]model.Record{}
	for _, r := range out {
		byName[r.PackageName] = r
	}
	if got := byName["crypto"]; got.Version != "3.0.3" || got.Confidence != "high" || got.InstallScope != "prod" {
		t.Errorf("crypto: %+v", got)
	}
	if got := byName["lints"]; got.InstallScope != "dev" {
		t.Errorf("lints: %+v", got)
	}
	// A path dependency has no pub.dev release to match an advisory to.
	if got := byName["my_local"]; got.Confidence != "low" {
		t.Errorf("path dep: %+v", got)
	}
	if byName["crypto"].Ecosystem != model.EcosystemPub {
		t.Errorf("ecosystem=%q", byName["crypto"].Ecosystem)
	}
	// The sdks: section must not become a package.
	if _, ok := byName["dart"]; ok {
		t.Error("sdks entry leaked into packages")
	}
}

func TestScanMixLock(t *testing.T) {
	body := `%{
  "jason": {:hex, :jason, "1.4.1", "hashabc", [:mix], [{:decimal, "~> 1.0 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: true]}], "hexpm", "hashdef"},
  "plug": {:hex, :plug, "1.16.1", "hash", [:mix], [], "hexpm", "hash2"},
  "my_fork": {:git, "https://github.com/example/my_fork.git", "abcdef", []},
}
`
	out := run(t, "mix.lock", body, (*Scanner).ScanMixLock)
	if len(out) != 3 {
		t.Fatalf("want 3 records, got %d: %+v", len(out), out)
	}
	byName := map[string]model.Record{}
	for _, r := range out {
		byName[r.PackageName] = r
	}
	if got := byName["jason"]; got.Version != "1.4.1" || got.Confidence != "high" {
		t.Errorf("jason: %+v", got)
	}
	if got := byName["plug"]; got.Version != "1.16.1" {
		t.Errorf("plug: %+v", got)
	}
	// A git dependency is real but has no hex.pm version.
	if got := byName["my_fork"]; got.Version != "" || got.Confidence != "low" {
		t.Errorf("git dep: %+v", got)
	}
	if byName["jason"].Ecosystem != model.EcosystemHex {
		t.Errorf("ecosystem=%q", byName["jason"].Ecosystem)
	}
}
