package pub

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/perplexityai/bumblebee/internal/model"
)

func TestScanPubspecLock(t *testing.T) {
	path := filepath.Join(t.TempDir(), "pubspec.lock")
	if err := os.WriteFile(path, []byte(`# Generated by pub
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: "abc"
      url: "https://pub.dev"
    source: hosted
    version: "3.4.10"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "1.1.2"
  my_local:
    dependency: "direct dev"
    description:
      path: "../local"
    source: path
    version: "0.0.1"
sdks:
  dart: ">=3.0.0 <4.0.0"
`), 0o644); err != nil {
		t.Fatal(err)
	}

	var got []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { got = append(got, r) }}
	if err := s.ScanPubspecLock(path, model.Record{}); err != nil {
		t.Fatal(err)
	}

	byName := map[string]model.Record{}
	for _, r := range got {
		byName[r.PackageName] = r
	}
	if len(byName) != 3 {
		t.Fatalf("got %d packages, want 3: %+v", len(byName), got)
	}

	// The nested `description: name:` must not overwrite the entry name,
	// and `sdks:` must not be read as a package.
	if _, ok := byName["dart"]; ok {
		t.Error("sdks entries must not be emitted as packages")
	}

	archive := byName["archive"]
	if archive.Version != "3.4.10" {
		t.Errorf("archive version = %q", archive.Version)
	}
	if archive.Ecosystem != model.EcosystemPub || archive.Confidence != "high" {
		t.Errorf("ecosystem/confidence = %q/%q", archive.Ecosystem, archive.Confidence)
	}
	if archive.DirectDependency == nil || *archive.DirectDependency {
		t.Error("transitive package should be flagged indirect")
	}

	http := byName["http"]
	if http.DirectDependency == nil || !*http.DirectDependency {
		t.Error("direct main package should be flagged direct")
	}

	// A path source is local code, not a registry release.
	local := byName["my_local"]
	if local.Confidence != "low" || local.InstallScope != "local" {
		t.Errorf("path package confidence/scope = %q/%q", local.Confidence, local.InstallScope)
	}
}

func TestScanPubspecLockEmptyFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "pubspec.lock")
	if err := os.WriteFile(path, []byte("packages:\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var got []model.Record
	s := &Scanner{MaxFileSize: 1 << 20, Emit: func(r model.Record) { got = append(got, r) }}
	if err := s.ScanPubspecLock(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Errorf("got %d records from an empty lock", len(got))
	}
}
