package maven

import (
	"archive/zip"
	"os"
	"path/filepath"
	"testing"

	"github.com/perplexityai/bumblebee/internal/model"
)

func newScanner() (*Scanner, *[]model.Record) {
	var got []model.Record
	s := &Scanner{
		MaxFileSize: 1 << 20,
		Emit:        func(r model.Record) { got = append(got, r) },
		Diag:        func(level, path, msg string) {},
	}
	return s, &got
}

func write(t *testing.T, dir, name, content string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestPredicates(t *testing.T) {
	if !IsGradleLockfile("gradle.lockfile") || !IsGradleLockfile("compile.gradle.lockfile") {
		t.Error("IsGradleLockfile")
	}
	if !IsSbtLock("build.sbt.lock") {
		t.Error("IsSbtLock")
	}
	for _, ok := range []string{"a.jar", "b.WAR", "c.ear"} {
		if !IsJavaArchive(ok) {
			t.Errorf("IsJavaArchive(%q) = false", ok)
		}
	}
	if IsJavaArchive("notes.txt") {
		t.Error("IsJavaArchive matched a text file")
	}
}

func TestScanGradleLockfile(t *testing.T) {
	dir := t.TempDir()
	path := write(t, dir, "gradle.lockfile", `# This is a Gradle generated file for dependency locking.
com.google.guava:guava:32.1.3-jre=compileClasspath,runtimeClasspath
org.slf4j:slf4j-api:2.0.9=runtimeClasspath
empty=annotationProcessor
`)
	s, got := newScanner()
	if err := s.ScanGradleLockfile(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(*got) != 2 {
		t.Fatalf("got %d records, want 2 (the 'empty=' line is not a package): %+v", len(*got), *got)
	}
	r := (*got)[0]
	if r.PackageName != "com.google.guava:guava" {
		t.Errorf("package = %q, want groupId:artifactId", r.PackageName)
	}
	if r.Version != "32.1.3-jre" {
		t.Errorf("version = %q", r.Version)
	}
	if r.Ecosystem != model.EcosystemMaven || r.Confidence != "high" {
		t.Errorf("ecosystem/confidence = %q/%q", r.Ecosystem, r.Confidence)
	}
}

func TestScanPomXMLResolvesPropertiesAndSkipsRanges(t *testing.T) {
	dir := t.TempDir()
	path := write(t, dir, "pom.xml", `<?xml version="1.0"?>
<project>
  <groupId>com.example</groupId>
  <artifactId>app</artifactId>
  <version>1.0.0</version>
  <properties>
    <junit.version>5.10.1</junit.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.14.0</version>
    </dependency>
    <dependency>
      <groupId>com.unresolved</groupId>
      <artifactId>thing</artifactId>
      <version>${missing.version}</version>
    </dependency>
  </dependencies>
</project>`)
	s, got := newScanner()
	if err := s.ScanPomXML(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	byName := map[string]model.Record{}
	for _, r := range *got {
		byName[r.PackageName] = r
	}
	if len(byName) != 2 {
		t.Fatalf("got %d records, want 2 (unresolved property must be skipped): %+v", len(byName), *got)
	}
	junit, ok := byName["org.junit.jupiter:junit-jupiter"]
	if !ok {
		t.Fatal("junit missing")
	}
	if junit.Version != "5.10.1" {
		t.Errorf("property was not resolved: version = %q", junit.Version)
	}
	if junit.InstallScope != "test" {
		t.Errorf("scope = %q, want test", junit.InstallScope)
	}
	// A pom is a declaration, not a resolved graph.
	if junit.Confidence != "medium" {
		t.Errorf("confidence = %q, want medium", junit.Confidence)
	}
	if _, ok := byName["com.unresolved:thing"]; ok {
		t.Error("unresolved ${missing.version} should not be emitted")
	}
}

func TestScanSbtLock(t *testing.T) {
	dir := t.TempDir()
	path := write(t, dir, "build.sbt.lock", `{
  "lockVersion": 1,
  "dependencies": [
    { "org": "org.typelevel", "name": "cats-core_2.13", "version": "2.10.0" }
  ]
}`)
	s, got := newScanner()
	if err := s.ScanSbtLock(path, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(*got) != 1 {
		t.Fatalf("got %d records, want 1", len(*got))
	}
	if (*got)[0].PackageName != "org.typelevel:cats-core_2.13" {
		t.Errorf("package = %q", (*got)[0].PackageName)
	}
}

func TestScanJavaArchiveReadsEmbeddedCoordinates(t *testing.T) {
	dir := t.TempDir()
	jarPath := filepath.Join(dir, "guava-32.1.3.jar")
	f, err := os.Create(jarPath)
	if err != nil {
		t.Fatal(err)
	}
	zw := zip.NewWriter(f)
	w, err := zw.Create("META-INF/maven/com.google.guava/guava/pom.properties")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := w.Write([]byte("#Generated by Maven\ngroupId=com.google.guava\nartifactId=guava\nversion=32.1.3-jre\n")); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	f.Close()

	s, got := newScanner()
	if err := s.ScanJavaArchive(jarPath, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(*got) != 1 {
		t.Fatalf("got %d records, want 1: %+v", len(*got), *got)
	}
	r := (*got)[0]
	if r.PackageName != "com.google.guava:guava" || r.Version != "32.1.3-jre" {
		t.Errorf("record = %q@%q", r.PackageName, r.Version)
	}
	if r.SourceType != "maven-archive" {
		t.Errorf("source type = %q", r.SourceType)
	}
}

func TestScanJavaArchiveWithoutCoordinatesEmitsNothing(t *testing.T) {
	dir := t.TempDir()
	jarPath := filepath.Join(dir, "shaded.jar")
	f, err := os.Create(jarPath)
	if err != nil {
		t.Fatal(err)
	}
	zw := zip.NewWriter(f)
	if _, err := zw.Create("com/example/Main.class"); err != nil {
		t.Fatal(err)
	}
	zw.Close()
	f.Close()

	s, got := newScanner()
	if err := s.ScanJavaArchive(jarPath, model.Record{}); err != nil {
		t.Fatal(err)
	}
	if len(*got) != 0 {
		t.Errorf("shaded jar without coordinates should yield no guess, got %+v", *got)
	}
}

func TestScanJavaArchiveOnNonZipIsNotAnError(t *testing.T) {
	dir := t.TempDir()
	path := write(t, dir, "broken.jar", "this is not a zip")
	s, got := newScanner()
	if err := s.ScanJavaArchive(path, model.Record{}); err != nil {
		t.Fatalf("unreadable archive should warn, not error: %v", err)
	}
	if len(*got) != 0 {
		t.Error("no records expected")
	}
}
